// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/maintenance-landing/InspectorFlow.tsx": () => import("../components/mockups/maintenance-landing/InspectorFlow.tsx"),
  "./components/mockups/maintenance-landing/Landing.tsx": () => import("../components/mockups/maintenance-landing/Landing.tsx")
};
